// Guards the swept zoning-layer manifest. It is generated by
// `npm run zoning:sweep`, but it is COMMITTED and read at runtime, so a bad
// entry would silently point the app at a service that cannot answer — worse
// than the honest "no official layer" fallback.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync(new URL('../src/data/zoning-layer-manifest.json', import.meta.url), 'utf8'));

const entries = Object.entries(manifest.counties || {}).flatMap(([state, counties]) =>
  Object.entries(counties).flatMap(([county, value]) => [
    ...(value.county ? [{ state, county, layer: value.county }] : []),
    ...((value.municipalities || []).map((m) => ({ state, county, layer: m }))),
  ]));

const isBareCode = (v) => /^[A-Z0-9]{1,6}(?:[-/.][A-Z0-9]{1,6}){0,3}$/.test(String(v || '').trim())
  && /[A-Z]/.test(String(v || ''));

test('the manifest actually contains verified layers', () => {
  assert.ok(entries.length > 0, 'manifest is empty — run npm run zoning:sweep');
});

test('every layer url resolves to a service plus a numeric sublayer', () => {
  for (const { state, county, layer } of entries) {
    assert.match(
      layer.layerUrl,
      /^https:\/\/.+\/(?:MapServer|FeatureServer)\/\d+$/i,
      `${state} ${county}: ${layer.layerUrl}`,
    );
  }
});

test('every layer records the field a code was actually read from', () => {
  for (const { state, county, layer } of entries) {
    assert.ok(layer.codeField, `${state} ${county} has no codeField`);
  }
});

test('every entry carries live proof: a point that returned a real code', () => {
  for (const { state, county, layer } of entries) {
    const sample = layer.sample || {};
    assert.ok(Number.isFinite(sample.lng) && Number.isFinite(sample.lat), `${state} ${county}: no sample point`);
    assert.ok(
      isBareCode(sample.code),
      `${state} ${county}: sample code ${JSON.stringify(sample.code)} is not a published code — a district NAME or placeholder must never be recorded`,
    );
  }
});

test('layers are served over https only', () => {
  for (const { layer } of entries) assert.ok(layer.layerUrl.startsWith('https://'), layer.layerUrl);
});
